---
title: "Time Series Econometrics (TSE)"
author: "Henri Nyberg"
date: "`r Sys.Date()`"
output:
   bookdown::html_document2:
    theme: cerulean
    css: styles-TSE.css
    toc: false
    toc_float: false
    number_sections: true
    header-includes:
      - \newcommand{\ubar}[1]{\mkern3mu\underline{\mkern-3mu#1\mkern-3mu}\mkern3mu}
---

<!-- Use JavaScript to Disable Right-Click -->
<script>
document.addEventListener('contextmenu', event => event.preventDefault());
</script>

<!-- Custom JavaScript for toggling code visibility -->
<script>
function toggleCode(id) {
  var x = document.getElementById(id);
  if (x.style.display === "none") {
    x.style.display = "block";
  } else {
    x.style.display = "none";
  }
}
</script>



<!-- Visibility selections. display: none;? 
  <style>

/* Initially hide elements */
.marginnotevideo {
  display: none;
}

.marginnote {
  display: none;
}

  </style>
-->


# Preface {-}

<a class="toggle-link" onclick="toggleCode('foreword')">Foreword</a>
<div id="foreword" style="display:none;">

This material is contained from various sources. The material is largely based on the materials of the many courses on time series analysis held by Professor emeritus Pentti Saikkonen at the University of Helsinki. Many thanks to him for giving access to the previous course materials, especially on the course *Stationaariset aikasarjat* (2015). Thanks also to Professor Mika Meitz and his lecture notes "Lecture Notes on Time Series Econometrics" concerning the English translation. 

- Aikasarja-analyysi / Time Series Analysis at the Univ. of Turku 2016-2025.


Other sources and potential references include the following:

- Brockwell, P.J. \& R.A. Davis (1996 or 2002). Introduction to Time Series and Forecasting. Springer (2002, 2nd ed.).

- Franses, P.H. \& D. van Dijk (2000). Non-linear time series models in empirical finance. Cambridge University Press.

- Hamilton, J. (1994). Time Series Analysis. Princeton University Press.

- L\"{u}tkepohl, H. \& M. Kr\"{a}tzig (2004). Applied Time Series Econometrics. Cambridge University Press.

- Tsay, R.S. (2010). Analysis of Financial Time Series. Wiley

- Verbeek, M. (2008). A Guide To Modern Econometrics. John Wiley \& Sons. Third Edition

These materials focus largely on univariate time series models, but we will also briefly consider the main points of multiple time series, specifically vector autoregressive (VAR) models and cointegration. Moreover, we will also consider some basics of machine learning techniques in time series econometrics. The empirical examples (carried out by RStudio) provide illustration of the theoretical basis. The empirical examples are mostly from economic and financial applications, but the methods are applicable in many other fields as well.

Some empirical examples are based on well-known journal articles:

- Hall, R.E. (1978). Stochastic implications of the life cycle-permanent income hypothesis: Theory and evidence. Journal of Political Economy, 86(6), 971--987.

- Stock, J.H & M.W. Watson (2001). Vector Autoregressions. Journal of Economic Perspectives, 15(4), 101--115.


Datasets and data sources used in this lecture manuscript:

- Shiller data: Robert Shiller's data on Irrational Exuberance

- FRED data

- quantmod R package

Thanks also to BSc Juho Pitkäranta for helping with translation and setting up this version. All remaining errors are by the author. 
</div>

&nbsp;

<a class="toggle-link" onclick="toggleCode('notation')">Notation</a> 
<div id="notation" style="display:none;">

On this course, we follow the following notational selections:

- We will use the same notation for random quantities and their realized values. The context should make the difference clear.

- In matrix calculations, vectors are interpreted as column vectors and we might also denote, for example, $y=\left[y_{1}\text{ }\cdots\text{ }y_{T}\right]^{\prime}$, where the superscripted comma denotes transpose of a vector (or elsewhere also of a matrix).

</div>

&nbsp;



